{% set version = '0.4.2' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-schoolmath
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/schoolmath_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/schoolmath/schoolmath_{{ version }}.tar.gz
  sha256: 67cfb937f95c680d4bd3a274a43bff847342f4b962cbe421de537a16dd8d1064

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('schoolmath')"           # [not win]
    - "\"%R%\" -e \"library('schoolmath')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=schoolmath
  license: GPL-2.0-or-later
  summary: Contains functions and datasets for math taught in school. A main focus is set to
    prime-calculation.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dillonroach

# Package: schoolmath
# Type: Package
# Title: Functions and Datasets for Math Used in School
# Authors@R: c(person(given="Jorg", family="groe Schlarmann", role=c("aut", "cre"), email="schlarmann@produnis.de"), person(given="Josef", family="Wienand", role=c("ctb"), email="jwienand@produnis.de"))
# Description: Contains functions and datasets for math taught in school. A main focus is set to prime-calculation.
# Version: 0.4.2
# Date: 2023-08-21
# License: GPL (>= 2)
# Depends: R (>= 2.10)
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# NeedsCompilation: no
# RoxygenNote: 7.2.3
# Packaged: 2023-08-21 12:43:11 UTC; produnis
# Author: Jorg groe Schlarmann [aut, cre], Josef Wienand [ctb]
# Maintainer: Jorg groe Schlarmann <schlarmann@produnis.de>
# Repository: CRAN
# Date/Publication: 2023-08-21 14:20:02 UTC
